manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
    
  include:
    - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view